version: '3'
services:
  frontend:
    container_name: hape-frontend
    restart: always
    build: ./frontend/
    volumes:
      - ./frontend:/src
    ports:
      - "3100:3000"

  api: # Node.js App
    container_name: hape-api
    restart: always
    build: ./api/
    volumes:
      - ./api:/src
    ports:
      - "3800:3500"
    networks:
      - hape
    depends_on:
      - mysql
      - redis
      - elasticsearch
  mysql:
    container_name: hape-mysql
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cY5KWGN3ek2Ky9YzyjNupmv7C
      MYSQL_DATABASE: hape_production
    ports:
      - "3320:3306"
    networks:
      - hape
  redis: # sudo sysctl vm.overcommit_memory=1
    container_name: hape-redis
    restart: always
    image: redis
    ports:
      - "6380:6379"
    networks:
      - hape

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: hape-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9210:9200"
    networks:
      - hape
  
networks:
  hape: