version: '3'
services:
  frontend:
    container_name: hape-frontend
    restart: always
    build: ./frontend/
    volumes:
      - ./frontend:/src
    ports:
      - "3100:3000"
    
  admin:
    container_name: hape-admin
    # restart: always
    build: ./admin/
    volumes:
      - ./admin:/src
    ports:
      - "3800:3800"

  api: # Node.js App
    container_name: hape-api
    restart: always
    build: ./api/
    volumes:
      - ./api:/src
    ports:
      - "3800:3500"
    networks:
      - hape
    depends_on:
      - mysql
      - redis
      - elasticsearch
  mysql:
    container_name: hape-mysql
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cY5KWGN3ek2Ky9YzyjNupmv7C
      MYSQL_DATABASE: hape_production
    ports:
      - "3320:3306"
    networks:
      - hape
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5438:5432"
    networks:
      - hape
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5433:80"
    networks:
      - hape

  redis: # sudo sysctl vm.overcommit_memory=1
    container_name: hape-redis
    restart: always
    image: redis
    ports:
      - "6380:6379"
    networks:
      - hape

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: hape-elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "path.repo=/usr/share/elasticsearch/backups"    
    volumes:
      - ./elasticsearch/backups:/usr/share/elasticsearch/backups
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9210:9200"
    networks:
      - hape
  
networks:
  hape: